### ISSUE TITLE
Starting the project mav_control using ACADOtoolkit in ROS- Link to a simple example

### ISSUE THREAD

**Issue by JavierPradoRomo2007** [ethz-asl/mav_control_rw#13]
Dear developers and researchers!

This work looks greate!, so I decided to recover many concepts from this project. I have tested this project, but I found many missing packages on it. I tasted on Ubuntu 16.0 and Gazebo 7. I cannot run the project, the only one stuff I would like to test is the ACADOtoolkit in ROS. I only checked the controller package, but I cannot run it as well. Can anybody help me with a simple project working with ACADO and ROS. I appreciate it so much.

Greatings 
Javier

**Comment by fmina** [comment]
ACADOtoolkit has nothing to do with ROS. the toolkit will generate a solver in C. 
Can you please tell us what are you trying to do exactly?
