### ISSUE TITLE
Typos in steady_state_calculation.cpp

### ISSUE THREAD

**Issue by alexbuyval** [ethz-asl/mav_control_rw#3]
Hi,

I faced with typos in steady_state_calculation.cpp [here](https://github.com/ethz-asl/mav_control_rw/blob/master/mav_linear_mpc/src/steady_state_calculation.cpp#L74)

I am sure these lines should be:
```
  assert(steadystate_state);
  assert(steadystate_input);
```
or you need to fix these names into method header.

**Comment by fmina** [comment]
Thanks, will push a fix.

**Comment by fmina** [comment]
fixed.
