### ISSUE TITLE
drift off/diverge when yaw 90 degree

### ISSUE THREAD

**Issue by fx815** [ethz-asl/mav_control_rw#30]
Hi! I am using the nonlinear MPC on a small drone controlled by Betaflight. I use RC signal to control the attitude and use vicon to estimate odometry. I did the system ID and some dynamic tuning and it hovers very accurately when have 0 degree yaw command. However, if I give command/pose a 90 degree yaw orientation, it turns to 90 degree and begin to drift like a spiral, then it reaches a sort of stable status and loiters. It is very strange because I have used this MPC on Pixhawk and M100, and they all flies fine. Any ideas why this is happening? Thanks.

Best regards,
Feng

**Comment by fx815** [comment]
Found the issue. The linear and angular velocity should be in body frame in the odometry message. I used world.

**Comment by caomuqing** [comment]
thanks for this, it helped resolving my issue as well!
