### ISSUE TITLE
Real hardware implementation

### ISSUE THREAD

**Issue by rapop** [ethz-asl/mav_control_rw#34]
Hi,

How should I proceed to implement this on real hardware with the hacked version of px4 firmware and hacked mavros?

- Do you have a node that publish on a mavros topic from command/roll_pitch_yawrate_thrust ?
- And on which mavros topic should I publish for the hacked version?

Thanks a lot.

**Comment by gajena** [comment]
follow this: https://github.com/ethz-asl/mav_tools_public/wiki
