### ISSUE TITLE
Query : Regarding the Reference Trajectory Input

### ISSUE THREAD

**Issue by Kavin-Kailash** [ethz-asl/mav_control_rw#38]
We are working on using MoveIt! for planning collision free trajectory for our UAV. We found that this package perfectly fills in the gap between MoveIt! and the low level controller on board the UAV. However as MoveIt! just outputs a trajectory with no accel / vel information, can this package still be used to generate attitude commands.

**Comment by afakharany93** [comment]
can you please tell us the answer of your question if you discovered it?
