### ISSUE TITLE
Question about moment of inertia.

### ISSUE THREAD

**Issue by tdnet12434** [ethz-asl/mav_control_rw#9]
First of all, thank you for this awesome framework!!
I know this is not an issue of this framework but i need some advice to find moment of inertia.
As far as i know, it can be calculated from many way such as 
1. by measuring the period of oscillation.
2. by accurate solidworks model or cad model.

These above ways can achieve accurate Ixx,Iyy,Izz but required hard work on every payload change. 
I have heard from someone that we can also estimate from fitted curve transfer function by excite the respect axis. This way is good enough to use in this framework? Any guide would be appreciate.
Thank you.

**Comment by fmina** [comment]
Hi,
In this framework we assume the existence of an attitude controller with first order dynamics. As the moment of inertia changes, the attitude loop dynamics might change depending on the attitude controller. The way we find the atttude dynamics is, as you said, by exciting each axis and doing a system identification. 

Here are useful scripts to do sysid https://github.com/ethz-asl/mav_system_identification
